
# Site settings
name: kentlee2.github.io
email: luoyan35714@126.com
author: kentlee2
url: 
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/kentlee2
port: 3333
baseurl: ""
description: Actually, less is more!
meta_description: 学而不思则罔，思而不学则殆。
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。
#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: luoyan35714
highlighter: Pygments

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : luoyan35714
    disqus :
        short_name :kent
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light